name: Gradle build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '11.0.1'
          distribution: 'zulu'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        run: ./gradlew build -x test
      - name: Tests
        run: ./gradlew test
